name: cppcheck

on: push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive

      - name: Install project deps
        run: |
          sudo apt-get update
          sudo apt-get -y -qq install libxrandr-dev mesa-common-dev libgl-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Build project deps deps
        run: |
          cd deps/glfw/
          mkdir build
          cd build
          cmake .. -DBUILD_SHARED_LIBS=ON
          make
          cd ../../

          cd cJSON
          mkdir build
          cd build
          cmake ..
          make
          cd ../../
        env:
          MAKEFLAGS: -j3

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get -y -qq install curl
          sudo apt-get -y -qq install clang-tidy cmake jq clang cppcheck
          python -m pip install scan-build

      - name: Update Path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Update compile database
        run: |
          make clean
          intercept-build make

      - name: run cppcheck
        run: cppcheck --enable=all --suppress=missingIncludeSystem --std=c99 --language=c --error-exitcode=1 src/*.c
