name: valgrind

on: push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive

      - name: Install project deps
        run: |
          sudo apt-get update
          sudo apt-get -y -qq install libxrandr-dev mesa-common-dev libgl-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Build project deps deps
        run: |
          cd deps/glfw/
          mkdir build
          cd build
          cmake .. -DBUILD_SHARED_LIBS=ON
          make
          cd ../../

          cd cJSON
          mkdir build
          cd build
          cmake ..
          make
          cd ../../
        env:
          MAKEFLAGS: -j3

      - name: Install step deps
        run: |
          sudo apt-get update
          sudo apt-get -y -qq install valgrind

      - name: Build
        run: make callgrind
        env:
          MAKEFLAGS: -j3

      - name: Run valgrind
        run: ./raytracer
